//! TLS on the client-facing plane: a pinned-CA client trains a full session
//! against a cluster whose client-facing listeners present the deployment's
//! server certificate, and a plaintext client is cleanly rejected by a TLS
//! aggregator.
//!
//! The fixtures under `pbr-server/tests/fixtures/tls/` are generated by
//! `deploy/hetzner/gen-certs.sh 127.0.0.1`: a self-signed CA plus one server
//! cert whose IP SAN is `127.0.0.1`, which is what rustls matches the endpoint
//! host against here.

use pbr_client::driver::{ClientSession, SessionParams, run_to_completion};
use pbr_client::jwt::mint;
use pbr_server::agg_config::AggregatorConfig;
use pbr_server::aggregator::{
    DatasetTable, RunningAggregator, SessionSpec, serve as serve_aggregator,
};
use pbr_server::config::{AuthConfig, ShareholderConfig, StaticKey, TlsConfig};
use pbr_server::shareholder::{RunningShareholder, serve as serve_shareholder};
use std::time::{Duration, Instant};

const ISS: &str = "https://test-issuer.local";
const AUD: &str = "pbr";
const KID: &str = "test-1";
const PRIV: &[u8] = include_bytes!("../../pbr-server/tests/fixtures/test_key.pem");
/// The CA the fixtures' server cert chains to; pinned by the client below.
const CA_PEM: &[u8] = include_bytes!("../../pbr-server/tests/fixtures/tls/ca.crt");

const THRESHOLD: usize = 2;

fn auth_cfg() -> AuthConfig {
    AuthConfig {
        issuer: ISS.into(),
        audience: AUD.into(),
        static_keys: vec![StaticKey {
            kid: KID.into(),
            public_key_pem_path: concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../pbr-server/tests/fixtures/test_key.pub.pem"
            )
            .into(),
        }],
        google_jwks_url: None,
    }
}

/// The deployment server cert + key from the shared fixtures.
fn tls_cfg() -> TlsConfig {
    TlsConfig {
        cert_path: concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../pbr-server/tests/fixtures/tls/server.crt"
        )
        .into(),
        key_path: concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../pbr-server/tests/fixtures/tls/server.key"
        )
        .into(),
    }
}

fn shareholder_cfg(x: u64) -> ShareholderConfig {
    ShareholderConfig {
        x_coord: x,
        min_clients: 1,
        listen: "127.0.0.1:0".parse().unwrap(),
        internal_listen: "127.0.0.1:0".parse().unwrap(),
        auth: auth_cfg(),
        tls: Some(tls_cfg()),
    }
}

/// A pinned-CA client completes a whole session over `https://127.0.0.1:<port>`
/// against a TLS cluster. The client-facing planes are TLS; the internal plane
/// stays plaintext loopback, and the aggregator gathers over it unchanged.
#[tokio::test]
async fn tls_session_round_trips_with_pinned_ca() {
    let mut client_eps = Vec::new();
    let mut internal_eps = Vec::new();
    let mut sh_handles = Vec::new();
    for x in 1..=3u64 {
        let RunningShareholder {
            client_addr,
            internal_addr,
            handle,
        } = serve_shareholder(shareholder_cfg(x)).await.unwrap();
        client_eps.push(format!("https://{client_addr}"));
        internal_eps.push(format!("http://{internal_addr}"));
        sh_handles.push(handle);
    }

    let RunningAggregator {
        addr: agg_addr,
        handle: agg_handle,
    } = serve_aggregator(AggregatorConfig {
        listen: "127.0.0.1:0".parse().unwrap(),
        internal_shareholder_endpoints: internal_eps,
        client_shareholder_endpoints: client_eps.clone(),
        threshold: THRESHOLD,
        auth: auth_cfg(),
        fcm: None,
        tls: Some(tls_cfg()),
        datasets: DatasetTable::default(),
        admin_token: None,
        state_path: ":memory:".into(),
        eval: None,
    })
    .await
    .unwrap();

    agg_handle
        .create_session(SessionSpec {
            dataset_id: String::new(),
            title: "tls test".into(),
            n_trees: 1,
            max_depth: 1,
            n_bins: 8,
            learning_rate: 0.3,
            lambda: 1.0,
            min_clients: 1,
            target_clients: 1,
            submission_window_ms: 2_000,
        })
        .expect("the session under test must be created");

    let token = mint(ISS, AUD, KID, "test-driver", 300, PRIV).unwrap();
    let agg_url = format!("https://{agg_addr}");

    run_to_completion(
        SessionParams {
            agg_endpoint: agg_url,
            shareholder_endpoints: Some(client_eps),
            token,
            records: vec![(vec![2.0, 1.0], 1.0)],
            threshold: Some(THRESHOLD),
            hide_path: true,
            ca_pem: Some(CA_PEM.to_vec()),
            session_id: None,
        },
        |_| {},
    )
    .await
    .expect("a pinned-CA client must complete the session over TLS");

    agg_handle.shutdown();
    for h in sh_handles {
        h.shutdown();
    }
}

/// A plaintext client against a TLS aggregator fails the handshake and surfaces
/// a clean error, bounded by the client's own RPC deadline rather than hanging.
#[tokio::test]
async fn plain_client_rejected_by_tls_server() {
    // Only the client-facing listener matters here; the round loop's
    // shareholder endpoints never need to be real (it fails in the background,
    // off the enroll path).
    let RunningAggregator {
        addr: agg_addr,
        handle: agg_handle,
    } = serve_aggregator(AggregatorConfig {
        listen: "127.0.0.1:0".parse().unwrap(),
        internal_shareholder_endpoints: vec!["http://127.0.0.1:1".into()],
        client_shareholder_endpoints: vec!["http://127.0.0.1:2".into()],
        threshold: 1,
        auth: auth_cfg(),
        fcm: None,
        tls: Some(tls_cfg()),
        datasets: DatasetTable::default(),
        admin_token: None,
        state_path: ":memory:".into(),
        eval: None,
    })
    .await
    .unwrap();

    let token = mint(ISS, AUD, KID, "test-driver", 300, PRIV).unwrap();
    // Plaintext http:// with no pinned CA against the TLS listener.
    let agg_url = format!("http://{agg_addr}");

    let started = Instant::now();
    let outcome = ClientSession::enroll(SessionParams {
        agg_endpoint: agg_url,
        shareholder_endpoints: Some(vec!["http://127.0.0.1:3".into()]),
        token,
        records: vec![(vec![1.0, 2.0], 0.0)],
        threshold: Some(1),
        hide_path: true,
        ca_pem: None,
        session_id: None,
    })
    .await;

    assert!(
        outcome.is_err(),
        "a plaintext client must be rejected by the TLS server, not enrolled"
    );
    assert!(
        started.elapsed() < Duration::from_secs(30),
        "the handshake failure must surface within the client's RPC deadline, not hang"
    );

    agg_handle.shutdown();
}
