// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 963593524;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__mobile__create_round_summary_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_round_summary_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::mobile::RoundSummary,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::mobile::create_round_summary_stream(api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__mobile__enroll_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "enroll_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_agg_endpoint = <String>::sse_decode(&mut deserializer);
            let api_id_token = <String>::sse_decode(&mut deserializer);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_ca_pem = <Option<Vec<u8>>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::mobile::enroll_session(
                                api_agg_endpoint,
                                api_id_token,
                                api_session_id,
                                api_ca_pem,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__mobile__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::mobile::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__mobile__list_sessions_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_sessions",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_agg_endpoint = <String>::sse_decode(&mut deserializer);
            let api_id_token = <String>::sse_decode(&mut deserializer);
            let api_ca_pem = <Option<Vec<u8>>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::mobile::list_sessions(
                                api_agg_endpoint,
                                api_id_token,
                                api_ca_pem,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__mobile__participate_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "participate",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_agg_endpoint = <String>::sse_decode(&mut deserializer);
            let api_id_token = <String>::sse_decode(&mut deserializer);
            let api_session_id = <Option<String>>::sse_decode(&mut deserializer);
            let api_feature_row = <Vec<f64>>::sse_decode(&mut deserializer);
            let api_label = <f64>::sse_decode(&mut deserializer);
            let api_hide_path = <bool>::sse_decode(&mut deserializer);
            let api_ca_pem = <Option<Vec<u8>>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::mobile::participate(
                                api_agg_endpoint,
                                api_id_token,
                                api_session_id,
                                api_feature_row,
                                api_label,
                                api_hide_path,
                                api_ca_pem,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__mobile__participate_batch_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "participate_batch",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_agg_endpoint = <String>::sse_decode(&mut deserializer);
            let api_id_token = <String>::sse_decode(&mut deserializer);
            let api_session_id = <Option<String>>::sse_decode(&mut deserializer);
            let api_records = <Vec<(Vec<f64>, f64)>>::sse_decode(&mut deserializer);
            let api_hide_path = <bool>::sse_decode(&mut deserializer);
            let api_ca_pem = <Option<Vec<u8>>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::mobile::participate_batch(
                                api_agg_endpoint,
                                api_id_token,
                                api_session_id,
                                api_records,
                                api_hide_path,
                                api_ca_pem,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__mobile__register_device_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "register_device",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_agg_endpoint = <String>::sse_decode(&mut deserializer);
            let api_id_token = <String>::sse_decode(&mut deserializer);
            let api_fcm_token = <String>::sse_decode(&mut deserializer);
            let api_platform = <crate::api::mobile::ClientPlatform>::sse_decode(&mut deserializer);
            let api_ca_pem = <Option<Vec<u8>>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::mobile::register_device(
                                api_agg_endpoint,
                                api_id_token,
                                api_fcm_token,
                                api_platform,
                                api_ca_pem,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__mobile__step_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "step_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_agg_endpoint = <String>::sse_decode(&mut deserializer);
            let api_id_token = <String>::sse_decode(&mut deserializer);
            let api_session_id = <Option<String>>::sse_decode(&mut deserializer);
            let api_records = <Vec<(Vec<f64>, f64)>>::sse_decode(&mut deserializer);
            let api_hide_path = <bool>::sse_decode(&mut deserializer);
            let api_ca_pem = <Option<Vec<u8>>>::sse_decode(&mut deserializer);
            let api_last_seen_round_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::mobile::step_session(
                                api_agg_endpoint,
                                api_id_token,
                                api_session_id,
                                api_records,
                                api_hide_path,
                                api_ca_pem,
                                api_last_seen_round_id,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::mobile::RoundSummary, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::mobile::BatchParticipationResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_records = <u32>::sse_decode(deserializer);
        let mut var_completed = <u32>::sse_decode(deserializer);
        let mut var_roundsTotal = <u32>::sse_decode(deserializer);
        let mut var_lastError = <Option<String>>::sse_decode(deserializer);
        return crate::api::mobile::BatchParticipationResult {
            records: var_records,
            completed: var_completed,
            rounds_total: var_roundsTotal,
            last_error: var_lastError,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::mobile::ClientPlatform {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::mobile::ClientPlatform::Android,
            1 => crate::api::mobile::ClientPlatform::Ios,
            _ => unreachable!("Invalid variant for ClientPlatform: {}", inner),
        };
    }
}

impl SseDecode for crate::api::mobile::EnrollResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_lastError = <Option<String>>::sse_decode(deserializer);
        return crate::api::mobile::EnrollResult {
            ok: var_ok,
            last_error: var_lastError,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::mobile::IdlePoll {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_pollUs = <u64>::sse_decode(deserializer);
        return crate::api::mobile::IdlePoll {
            session_id: var_sessionId,
            poll_us: var_pollUs,
        };
    }
}

impl SseDecode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<(Vec<f64>, f64)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<(Vec<f64>, f64)>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::mobile::SessionSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::mobile::SessionSummary>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::mobile::IdlePoll> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::mobile::IdlePoll>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::mobile::RoundSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::mobile::RoundSummary>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<u8>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::mobile::ParticipationResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_completed = <bool>::sse_decode(deserializer);
        let mut var_roundsSubmitted = <u32>::sse_decode(deserializer);
        let mut var_lastError = <Option<String>>::sse_decode(deserializer);
        let mut var_computeUs = <u64>::sse_decode(deserializer);
        let mut var_submitUs = <u64>::sse_decode(deserializer);
        return crate::api::mobile::ParticipationResult {
            completed: var_completed,
            rounds_submitted: var_roundsSubmitted,
            last_error: var_lastError,
            compute_us: var_computeUs,
            submit_us: var_submitUs,
        };
    }
}

impl SseDecode for (Vec<f64>, f64) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <Vec<f64>>::sse_decode(deserializer);
        let mut var_field1 = <f64>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for crate::api::mobile::RegisterResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_lastError = <Option<String>>::sse_decode(deserializer);
        return crate::api::mobile::RegisterResult {
            ok: var_ok,
            last_error: var_lastError,
        };
    }
}

impl SseDecode for crate::api::mobile::RoundKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::mobile::RoundKind::Stats,
            1 => crate::api::mobile::RoundKind::Gradient,
            _ => unreachable!("Invalid variant for RoundKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::mobile::RoundOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::mobile::RoundOutcome::Submitted,
            1 => crate::api::mobile::RoundOutcome::BelowThreshold,
            _ => unreachable!("Invalid variant for RoundOutcome: {}", inner),
        };
    }
}

impl SseDecode for crate::api::mobile::RoundStepOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::mobile::RoundStepOutcome::Submitted,
            1 => crate::api::mobile::RoundStepOutcome::NothingNew,
            2 => crate::api::mobile::RoundStepOutcome::Completed,
            3 => crate::api::mobile::RoundStepOutcome::Failed,
            4 => crate::api::mobile::RoundStepOutcome::Error,
            _ => unreachable!("Invalid variant for RoundStepOutcome: {}", inner),
        };
    }
}

impl SseDecode for crate::api::mobile::RoundStepResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outcome = <crate::api::mobile::RoundStepOutcome>::sse_decode(deserializer);
        let mut var_roundId = <u64>::sse_decode(deserializer);
        let mut var_sessionId = <Option<String>>::sse_decode(deserializer);
        let mut var_lastSeenRoundId = <u64>::sse_decode(deserializer);
        let mut var_summary = <Option<crate::api::mobile::RoundSummary>>::sse_decode(deserializer);
        let mut var_idle = <Option<crate::api::mobile::IdlePoll>>::sse_decode(deserializer);
        let mut var_lastError = <Option<String>>::sse_decode(deserializer);
        return crate::api::mobile::RoundStepResult {
            outcome: var_outcome,
            round_id: var_roundId,
            session_id: var_sessionId,
            last_seen_round_id: var_lastSeenRoundId,
            summary: var_summary,
            idle: var_idle,
            last_error: var_lastError,
        };
    }
}

impl SseDecode for crate::api::mobile::RoundSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_roundId = <u64>::sse_decode(deserializer);
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_nRecords = <u32>::sse_decode(deserializer);
        let mut var_roundKind = <crate::api::mobile::RoundKind>::sse_decode(deserializer);
        let mut var_treeIdx = <Option<u32>>::sse_decode(deserializer);
        let mut var_depth = <Option<u32>>::sse_decode(deserializer);
        let mut var_pollUs = <u64>::sse_decode(deserializer);
        let mut var_computeUs = <u64>::sse_decode(deserializer);
        let mut var_submitUs = <u64>::sse_decode(deserializer);
        let mut var_txBytes = <u64>::sse_decode(deserializer);
        let mut var_rxBytes = <u64>::sse_decode(deserializer);
        let mut var_nPeersAttempted = <u32>::sse_decode(deserializer);
        let mut var_nPeersAccepted = <u32>::sse_decode(deserializer);
        let mut var_outcome = <crate::api::mobile::RoundOutcome>::sse_decode(deserializer);
        let mut var_lastError = <Option<String>>::sse_decode(deserializer);
        return crate::api::mobile::RoundSummary {
            round_id: var_roundId,
            session_id: var_sessionId,
            n_records: var_nRecords,
            round_kind: var_roundKind,
            tree_idx: var_treeIdx,
            depth: var_depth,
            poll_us: var_pollUs,
            compute_us: var_computeUs,
            submit_us: var_submitUs,
            tx_bytes: var_txBytes,
            rx_bytes: var_rxBytes,
            n_peers_attempted: var_nPeersAttempted,
            n_peers_accepted: var_nPeersAccepted,
            outcome: var_outcome,
            last_error: var_lastError,
        };
    }
}

impl SseDecode for crate::api::mobile::SessionListResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessions = <Vec<crate::api::mobile::SessionSummary>>::sse_decode(deserializer);
        let mut var_lastError = <Option<String>>::sse_decode(deserializer);
        return crate::api::mobile::SessionListResult {
            sessions: var_sessions,
            last_error: var_lastError,
        };
    }
}

impl SseDecode for crate::api::mobile::SessionPhase {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::mobile::SessionPhase::StatsPending,
            1 => crate::api::mobile::SessionPhase::Training,
            2 => crate::api::mobile::SessionPhase::Completed,
            3 => crate::api::mobile::SessionPhase::Failed,
            _ => unreachable!("Invalid variant for SessionPhase: {}", inner),
        };
    }
}

impl SseDecode for crate::api::mobile::SessionSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_phase = <crate::api::mobile::SessionPhase>::sse_decode(deserializer);
        let mut var_nFeatures = <u32>::sse_decode(deserializer);
        let mut var_datasetId = <String>::sse_decode(deserializer);
        return crate::api::mobile::SessionSummary {
            session_id: var_sessionId,
            phase: var_phase,
            n_features: var_nFeatures,
            dataset_id: var_datasetId,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__mobile__create_round_summary_stream_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => wire__crate__api__mobile__enroll_session_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__mobile__init_app_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__mobile__list_sessions_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__mobile__participate_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__mobile__participate_batch_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__mobile__register_device_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__mobile__step_session_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::BatchParticipationResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.records.into_into_dart().into_dart(),
            self.completed.into_into_dart().into_dart(),
            self.rounds_total.into_into_dart().into_dart(),
            self.last_error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::BatchParticipationResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::BatchParticipationResult>
    for crate::api::mobile::BatchParticipationResult
{
    fn into_into_dart(self) -> crate::api::mobile::BatchParticipationResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::ClientPlatform {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Android => 0.into_dart(),
            Self::Ios => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::ClientPlatform
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::ClientPlatform>
    for crate::api::mobile::ClientPlatform
{
    fn into_into_dart(self) -> crate::api::mobile::ClientPlatform {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::EnrollResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.last_error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::EnrollResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::EnrollResult>
    for crate::api::mobile::EnrollResult
{
    fn into_into_dart(self) -> crate::api::mobile::EnrollResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::IdlePoll {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.poll_us.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::mobile::IdlePoll {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::IdlePoll>
    for crate::api::mobile::IdlePoll
{
    fn into_into_dart(self) -> crate::api::mobile::IdlePoll {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::ParticipationResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.completed.into_into_dart().into_dart(),
            self.rounds_submitted.into_into_dart().into_dart(),
            self.last_error.into_into_dart().into_dart(),
            self.compute_us.into_into_dart().into_dart(),
            self.submit_us.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::ParticipationResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::ParticipationResult>
    for crate::api::mobile::ParticipationResult
{
    fn into_into_dart(self) -> crate::api::mobile::ParticipationResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::RegisterResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.last_error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::RegisterResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::RegisterResult>
    for crate::api::mobile::RegisterResult
{
    fn into_into_dart(self) -> crate::api::mobile::RegisterResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::RoundKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Stats => 0.into_dart(),
            Self::Gradient => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::mobile::RoundKind {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::RoundKind>
    for crate::api::mobile::RoundKind
{
    fn into_into_dart(self) -> crate::api::mobile::RoundKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::RoundOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Submitted => 0.into_dart(),
            Self::BelowThreshold => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::RoundOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::RoundOutcome>
    for crate::api::mobile::RoundOutcome
{
    fn into_into_dart(self) -> crate::api::mobile::RoundOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::RoundStepOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Submitted => 0.into_dart(),
            Self::NothingNew => 1.into_dart(),
            Self::Completed => 2.into_dart(),
            Self::Failed => 3.into_dart(),
            Self::Error => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::RoundStepOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::RoundStepOutcome>
    for crate::api::mobile::RoundStepOutcome
{
    fn into_into_dart(self) -> crate::api::mobile::RoundStepOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::RoundStepResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.outcome.into_into_dart().into_dart(),
            self.round_id.into_into_dart().into_dart(),
            self.session_id.into_into_dart().into_dart(),
            self.last_seen_round_id.into_into_dart().into_dart(),
            self.summary.into_into_dart().into_dart(),
            self.idle.into_into_dart().into_dart(),
            self.last_error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::RoundStepResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::RoundStepResult>
    for crate::api::mobile::RoundStepResult
{
    fn into_into_dart(self) -> crate::api::mobile::RoundStepResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::RoundSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.round_id.into_into_dart().into_dart(),
            self.session_id.into_into_dart().into_dart(),
            self.n_records.into_into_dart().into_dart(),
            self.round_kind.into_into_dart().into_dart(),
            self.tree_idx.into_into_dart().into_dart(),
            self.depth.into_into_dart().into_dart(),
            self.poll_us.into_into_dart().into_dart(),
            self.compute_us.into_into_dart().into_dart(),
            self.submit_us.into_into_dart().into_dart(),
            self.tx_bytes.into_into_dart().into_dart(),
            self.rx_bytes.into_into_dart().into_dart(),
            self.n_peers_attempted.into_into_dart().into_dart(),
            self.n_peers_accepted.into_into_dart().into_dart(),
            self.outcome.into_into_dart().into_dart(),
            self.last_error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::RoundSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::RoundSummary>
    for crate::api::mobile::RoundSummary
{
    fn into_into_dart(self) -> crate::api::mobile::RoundSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::SessionListResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.sessions.into_into_dart().into_dart(),
            self.last_error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::SessionListResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::SessionListResult>
    for crate::api::mobile::SessionListResult
{
    fn into_into_dart(self) -> crate::api::mobile::SessionListResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::SessionPhase {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::StatsPending => 0.into_dart(),
            Self::Training => 1.into_dart(),
            Self::Completed => 2.into_dart(),
            Self::Failed => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::SessionPhase
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::SessionPhase>
    for crate::api::mobile::SessionPhase
{
    fn into_into_dart(self) -> crate::api::mobile::SessionPhase {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mobile::SessionSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.phase.into_into_dart().into_dart(),
            self.n_features.into_into_dart().into_dart(),
            self.dataset_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mobile::SessionSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mobile::SessionSummary>
    for crate::api::mobile::SessionSummary
{
    fn into_into_dart(self) -> crate::api::mobile::SessionSummary {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::mobile::RoundSummary, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::mobile::BatchParticipationResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.records, serializer);
        <u32>::sse_encode(self.completed, serializer);
        <u32>::sse_encode(self.rounds_total, serializer);
        <Option<String>>::sse_encode(self.last_error, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::mobile::ClientPlatform {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::mobile::ClientPlatform::Android => 0,
                crate::api::mobile::ClientPlatform::Ios => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::mobile::EnrollResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <Option<String>>::sse_encode(self.last_error, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::mobile::IdlePoll {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <u64>::sse_encode(self.poll_us, serializer);
    }
}

impl SseEncode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<(Vec<f64>, f64)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <(Vec<f64>, f64)>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::mobile::SessionSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::mobile::SessionSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::mobile::IdlePoll> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::mobile::IdlePoll>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::mobile::RoundSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::mobile::RoundSummary>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<u8>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::mobile::ParticipationResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.completed, serializer);
        <u32>::sse_encode(self.rounds_submitted, serializer);
        <Option<String>>::sse_encode(self.last_error, serializer);
        <u64>::sse_encode(self.compute_us, serializer);
        <u64>::sse_encode(self.submit_us, serializer);
    }
}

impl SseEncode for (Vec<f64>, f64) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<f64>>::sse_encode(self.0, serializer);
        <f64>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for crate::api::mobile::RegisterResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <Option<String>>::sse_encode(self.last_error, serializer);
    }
}

impl SseEncode for crate::api::mobile::RoundKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::mobile::RoundKind::Stats => 0,
                crate::api::mobile::RoundKind::Gradient => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::mobile::RoundOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::mobile::RoundOutcome::Submitted => 0,
                crate::api::mobile::RoundOutcome::BelowThreshold => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::mobile::RoundStepOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::mobile::RoundStepOutcome::Submitted => 0,
                crate::api::mobile::RoundStepOutcome::NothingNew => 1,
                crate::api::mobile::RoundStepOutcome::Completed => 2,
                crate::api::mobile::RoundStepOutcome::Failed => 3,
                crate::api::mobile::RoundStepOutcome::Error => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::mobile::RoundStepResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::mobile::RoundStepOutcome>::sse_encode(self.outcome, serializer);
        <u64>::sse_encode(self.round_id, serializer);
        <Option<String>>::sse_encode(self.session_id, serializer);
        <u64>::sse_encode(self.last_seen_round_id, serializer);
        <Option<crate::api::mobile::RoundSummary>>::sse_encode(self.summary, serializer);
        <Option<crate::api::mobile::IdlePoll>>::sse_encode(self.idle, serializer);
        <Option<String>>::sse_encode(self.last_error, serializer);
    }
}

impl SseEncode for crate::api::mobile::RoundSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.round_id, serializer);
        <String>::sse_encode(self.session_id, serializer);
        <u32>::sse_encode(self.n_records, serializer);
        <crate::api::mobile::RoundKind>::sse_encode(self.round_kind, serializer);
        <Option<u32>>::sse_encode(self.tree_idx, serializer);
        <Option<u32>>::sse_encode(self.depth, serializer);
        <u64>::sse_encode(self.poll_us, serializer);
        <u64>::sse_encode(self.compute_us, serializer);
        <u64>::sse_encode(self.submit_us, serializer);
        <u64>::sse_encode(self.tx_bytes, serializer);
        <u64>::sse_encode(self.rx_bytes, serializer);
        <u32>::sse_encode(self.n_peers_attempted, serializer);
        <u32>::sse_encode(self.n_peers_accepted, serializer);
        <crate::api::mobile::RoundOutcome>::sse_encode(self.outcome, serializer);
        <Option<String>>::sse_encode(self.last_error, serializer);
    }
}

impl SseEncode for crate::api::mobile::SessionListResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::mobile::SessionSummary>>::sse_encode(self.sessions, serializer);
        <Option<String>>::sse_encode(self.last_error, serializer);
    }
}

impl SseEncode for crate::api::mobile::SessionPhase {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::mobile::SessionPhase::StatsPending => 0,
                crate::api::mobile::SessionPhase::Training => 1,
                crate::api::mobile::SessionPhase::Completed => 2,
                crate::api::mobile::SessionPhase::Failed => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::mobile::SessionSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <crate::api::mobile::SessionPhase>::sse_encode(self.phase, serializer);
        <u32>::sse_encode(self.n_features, serializer);
        <String>::sse_encode(self.dataset_id, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
