// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mobile.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiMobileInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 963593524;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_privateboost_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<RoundSummary> crateApiMobileCreateRoundSummaryStream();

  Future<EnrollResult> crateApiMobileEnrollSession({
    required String aggEndpoint,
    required String idToken,
    required String sessionId,
    Uint8List? caPem,
  });

  Future<void> crateApiMobileInitApp();

  Future<SessionListResult> crateApiMobileListSessions({
    required String aggEndpoint,
    required String idToken,
    Uint8List? caPem,
  });

  Future<ParticipationResult> crateApiMobileParticipate({
    required String aggEndpoint,
    required String idToken,
    String? sessionId,
    required List<double> featureRow,
    required double label,
    required bool hidePath,
    Uint8List? caPem,
  });

  Future<BatchParticipationResult> crateApiMobileParticipateBatch({
    required String aggEndpoint,
    required String idToken,
    String? sessionId,
    required List<(Float64List, double)> records,
    required bool hidePath,
    Uint8List? caPem,
  });

  Future<RegisterResult> crateApiMobileRegisterDevice({
    required String aggEndpoint,
    required String idToken,
    required String fcmToken,
    required ClientPlatform platform,
    Uint8List? caPem,
  });

  Future<RoundStepResult> crateApiMobileStepSession({
    required String aggEndpoint,
    required String idToken,
    String? sessionId,
    required List<(Float64List, double)> records,
    required bool hidePath,
    Uint8List? caPem,
    required BigInt lastSeenRoundId,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<RoundSummary> crateApiMobileCreateRoundSummaryStream() {
    final sink = RustStreamSink<RoundSummary>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_round_summary_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiMobileCreateRoundSummaryStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMobileCreateRoundSummaryStreamConstMeta =>
      const TaskConstMeta(
        debugName: "create_round_summary_stream",
        argNames: ["sink"],
      );

  @override
  Future<EnrollResult> crateApiMobileEnrollSession({
    required String aggEndpoint,
    required String idToken,
    required String sessionId,
    Uint8List? caPem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(aggEndpoint, serializer);
          sse_encode_String(idToken, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_opt_list_prim_u_8_strict(caPem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_enroll_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMobileEnrollSessionConstMeta,
        argValues: [aggEndpoint, idToken, sessionId, caPem],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMobileEnrollSessionConstMeta =>
      const TaskConstMeta(
        debugName: "enroll_session",
        argNames: ["aggEndpoint", "idToken", "sessionId", "caPem"],
      );

  @override
  Future<void> crateApiMobileInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMobileInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMobileInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<SessionListResult> crateApiMobileListSessions({
    required String aggEndpoint,
    required String idToken,
    Uint8List? caPem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(aggEndpoint, serializer);
          sse_encode_String(idToken, serializer);
          sse_encode_opt_list_prim_u_8_strict(caPem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_list_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMobileListSessionsConstMeta,
        argValues: [aggEndpoint, idToken, caPem],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMobileListSessionsConstMeta => const TaskConstMeta(
    debugName: "list_sessions",
    argNames: ["aggEndpoint", "idToken", "caPem"],
  );

  @override
  Future<ParticipationResult> crateApiMobileParticipate({
    required String aggEndpoint,
    required String idToken,
    String? sessionId,
    required List<double> featureRow,
    required double label,
    required bool hidePath,
    Uint8List? caPem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(aggEndpoint, serializer);
          sse_encode_String(idToken, serializer);
          sse_encode_opt_String(sessionId, serializer);
          sse_encode_list_prim_f_64_loose(featureRow, serializer);
          sse_encode_f_64(label, serializer);
          sse_encode_bool(hidePath, serializer);
          sse_encode_opt_list_prim_u_8_strict(caPem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_participation_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMobileParticipateConstMeta,
        argValues: [
          aggEndpoint,
          idToken,
          sessionId,
          featureRow,
          label,
          hidePath,
          caPem,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMobileParticipateConstMeta => const TaskConstMeta(
    debugName: "participate",
    argNames: [
      "aggEndpoint",
      "idToken",
      "sessionId",
      "featureRow",
      "label",
      "hidePath",
      "caPem",
    ],
  );

  @override
  Future<BatchParticipationResult> crateApiMobileParticipateBatch({
    required String aggEndpoint,
    required String idToken,
    String? sessionId,
    required List<(Float64List, double)> records,
    required bool hidePath,
    Uint8List? caPem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(aggEndpoint, serializer);
          sse_encode_String(idToken, serializer);
          sse_encode_opt_String(sessionId, serializer);
          sse_encode_list_record_list_prim_f_64_strict_f_64(
            records,
            serializer,
          );
          sse_encode_bool(hidePath, serializer);
          sse_encode_opt_list_prim_u_8_strict(caPem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_batch_participation_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMobileParticipateBatchConstMeta,
        argValues: [aggEndpoint, idToken, sessionId, records, hidePath, caPem],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMobileParticipateBatchConstMeta =>
      const TaskConstMeta(
        debugName: "participate_batch",
        argNames: [
          "aggEndpoint",
          "idToken",
          "sessionId",
          "records",
          "hidePath",
          "caPem",
        ],
      );

  @override
  Future<RegisterResult> crateApiMobileRegisterDevice({
    required String aggEndpoint,
    required String idToken,
    required String fcmToken,
    required ClientPlatform platform,
    Uint8List? caPem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(aggEndpoint, serializer);
          sse_encode_String(idToken, serializer);
          sse_encode_String(fcmToken, serializer);
          sse_encode_client_platform(platform, serializer);
          sse_encode_opt_list_prim_u_8_strict(caPem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_register_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMobileRegisterDeviceConstMeta,
        argValues: [aggEndpoint, idToken, fcmToken, platform, caPem],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMobileRegisterDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "register_device",
        argNames: ["aggEndpoint", "idToken", "fcmToken", "platform", "caPem"],
      );

  @override
  Future<RoundStepResult> crateApiMobileStepSession({
    required String aggEndpoint,
    required String idToken,
    String? sessionId,
    required List<(Float64List, double)> records,
    required bool hidePath,
    Uint8List? caPem,
    required BigInt lastSeenRoundId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(aggEndpoint, serializer);
          sse_encode_String(idToken, serializer);
          sse_encode_opt_String(sessionId, serializer);
          sse_encode_list_record_list_prim_f_64_strict_f_64(
            records,
            serializer,
          );
          sse_encode_bool(hidePath, serializer);
          sse_encode_opt_list_prim_u_8_strict(caPem, serializer);
          sse_encode_u_64(lastSeenRoundId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_round_step_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMobileStepSessionConstMeta,
        argValues: [
          aggEndpoint,
          idToken,
          sessionId,
          records,
          hidePath,
          caPem,
          lastSeenRoundId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMobileStepSessionConstMeta => const TaskConstMeta(
    debugName: "step_session",
    argNames: [
      "aggEndpoint",
      "idToken",
      "sessionId",
      "records",
      "hidePath",
      "caPem",
      "lastSeenRoundId",
    ],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<RoundSummary> dco_decode_StreamSink_round_summary_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BatchParticipationResult dco_decode_batch_participation_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BatchParticipationResult(
      records: dco_decode_u_32(arr[0]),
      completed: dco_decode_u_32(arr[1]),
      roundsTotal: dco_decode_u_32(arr[2]),
      lastError: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  IdlePoll dco_decode_box_autoadd_idle_poll(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_idle_poll(raw);
  }

  @protected
  RoundSummary dco_decode_box_autoadd_round_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_round_summary(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ClientPlatform dco_decode_client_platform(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClientPlatform.values[raw as int];
  }

  @protected
  EnrollResult dco_decode_enroll_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EnrollResult(
      ok: dco_decode_bool(arr[0]),
      lastError: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  IdlePoll dco_decode_idle_poll(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdlePoll(
      sessionId: dco_decode_String(arr[0]),
      pollUs: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(Float64List, double)> dco_decode_list_record_list_prim_f_64_strict_f_64(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_list_prim_f_64_strict_f_64)
        .toList();
  }

  @protected
  List<SessionSummary> dco_decode_list_session_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_session_summary).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  IdlePoll? dco_decode_opt_box_autoadd_idle_poll(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_idle_poll(raw);
  }

  @protected
  RoundSummary? dco_decode_opt_box_autoadd_round_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_round_summary(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  ParticipationResult dco_decode_participation_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ParticipationResult(
      completed: dco_decode_bool(arr[0]),
      roundsSubmitted: dco_decode_u_32(arr[1]),
      lastError: dco_decode_opt_String(arr[2]),
      computeUs: dco_decode_u_64(arr[3]),
      submitUs: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  (Float64List, double) dco_decode_record_list_prim_f_64_strict_f_64(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_list_prim_f_64_strict(arr[0]), dco_decode_f_64(arr[1]));
  }

  @protected
  RegisterResult dco_decode_register_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RegisterResult(
      ok: dco_decode_bool(arr[0]),
      lastError: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  RoundKind dco_decode_round_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RoundKind.values[raw as int];
  }

  @protected
  RoundOutcome dco_decode_round_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RoundOutcome.values[raw as int];
  }

  @protected
  RoundStepOutcome dco_decode_round_step_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RoundStepOutcome.values[raw as int];
  }

  @protected
  RoundStepResult dco_decode_round_step_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RoundStepResult(
      outcome: dco_decode_round_step_outcome(arr[0]),
      roundId: dco_decode_u_64(arr[1]),
      sessionId: dco_decode_opt_String(arr[2]),
      lastSeenRoundId: dco_decode_u_64(arr[3]),
      summary: dco_decode_opt_box_autoadd_round_summary(arr[4]),
      idle: dco_decode_opt_box_autoadd_idle_poll(arr[5]),
      lastError: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  RoundSummary dco_decode_round_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return RoundSummary(
      roundId: dco_decode_u_64(arr[0]),
      sessionId: dco_decode_String(arr[1]),
      nRecords: dco_decode_u_32(arr[2]),
      roundKind: dco_decode_round_kind(arr[3]),
      treeIdx: dco_decode_opt_box_autoadd_u_32(arr[4]),
      depth: dco_decode_opt_box_autoadd_u_32(arr[5]),
      pollUs: dco_decode_u_64(arr[6]),
      computeUs: dco_decode_u_64(arr[7]),
      submitUs: dco_decode_u_64(arr[8]),
      txBytes: dco_decode_u_64(arr[9]),
      rxBytes: dco_decode_u_64(arr[10]),
      nPeersAttempted: dco_decode_u_32(arr[11]),
      nPeersAccepted: dco_decode_u_32(arr[12]),
      outcome: dco_decode_round_outcome(arr[13]),
      lastError: dco_decode_opt_String(arr[14]),
    );
  }

  @protected
  SessionListResult dco_decode_session_list_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SessionListResult(
      sessions: dco_decode_list_session_summary(arr[0]),
      lastError: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  SessionPhase dco_decode_session_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionPhase.values[raw as int];
  }

  @protected
  SessionSummary dco_decode_session_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SessionSummary(
      sessionId: dco_decode_String(arr[0]),
      phase: dco_decode_session_phase(arr[1]),
      nFeatures: dco_decode_u_32(arr[2]),
      datasetId: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<RoundSummary> sse_decode_StreamSink_round_summary_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BatchParticipationResult sse_decode_batch_participation_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_records = sse_decode_u_32(deserializer);
    var var_completed = sse_decode_u_32(deserializer);
    var var_roundsTotal = sse_decode_u_32(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    return BatchParticipationResult(
      records: var_records,
      completed: var_completed,
      roundsTotal: var_roundsTotal,
      lastError: var_lastError,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  IdlePoll sse_decode_box_autoadd_idle_poll(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_idle_poll(deserializer));
  }

  @protected
  RoundSummary sse_decode_box_autoadd_round_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_round_summary(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  ClientPlatform sse_decode_client_platform(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ClientPlatform.values[inner];
  }

  @protected
  EnrollResult sse_decode_enroll_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    return EnrollResult(ok: var_ok, lastError: var_lastError);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  IdlePoll sse_decode_idle_poll(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_pollUs = sse_decode_u_64(deserializer);
    return IdlePoll(sessionId: var_sessionId, pollUs: var_pollUs);
  }

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(Float64List, double)> sse_decode_list_record_list_prim_f_64_strict_f_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(Float64List, double)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_list_prim_f_64_strict_f_64(deserializer));
    }
    return ans_;
  }

  @protected
  List<SessionSummary> sse_decode_list_session_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SessionSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_session_summary(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  IdlePoll? sse_decode_opt_box_autoadd_idle_poll(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_idle_poll(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RoundSummary? sse_decode_opt_box_autoadd_round_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_round_summary(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParticipationResult sse_decode_participation_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_completed = sse_decode_bool(deserializer);
    var var_roundsSubmitted = sse_decode_u_32(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    var var_computeUs = sse_decode_u_64(deserializer);
    var var_submitUs = sse_decode_u_64(deserializer);
    return ParticipationResult(
      completed: var_completed,
      roundsSubmitted: var_roundsSubmitted,
      lastError: var_lastError,
      computeUs: var_computeUs,
      submitUs: var_submitUs,
    );
  }

  @protected
  (Float64List, double) sse_decode_record_list_prim_f_64_strict_f_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_list_prim_f_64_strict(deserializer);
    var var_field1 = sse_decode_f_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RegisterResult sse_decode_register_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    return RegisterResult(ok: var_ok, lastError: var_lastError);
  }

  @protected
  RoundKind sse_decode_round_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RoundKind.values[inner];
  }

  @protected
  RoundOutcome sse_decode_round_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RoundOutcome.values[inner];
  }

  @protected
  RoundStepOutcome sse_decode_round_step_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RoundStepOutcome.values[inner];
  }

  @protected
  RoundStepResult sse_decode_round_step_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outcome = sse_decode_round_step_outcome(deserializer);
    var var_roundId = sse_decode_u_64(deserializer);
    var var_sessionId = sse_decode_opt_String(deserializer);
    var var_lastSeenRoundId = sse_decode_u_64(deserializer);
    var var_summary = sse_decode_opt_box_autoadd_round_summary(deserializer);
    var var_idle = sse_decode_opt_box_autoadd_idle_poll(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    return RoundStepResult(
      outcome: var_outcome,
      roundId: var_roundId,
      sessionId: var_sessionId,
      lastSeenRoundId: var_lastSeenRoundId,
      summary: var_summary,
      idle: var_idle,
      lastError: var_lastError,
    );
  }

  @protected
  RoundSummary sse_decode_round_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roundId = sse_decode_u_64(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_nRecords = sse_decode_u_32(deserializer);
    var var_roundKind = sse_decode_round_kind(deserializer);
    var var_treeIdx = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_depth = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_pollUs = sse_decode_u_64(deserializer);
    var var_computeUs = sse_decode_u_64(deserializer);
    var var_submitUs = sse_decode_u_64(deserializer);
    var var_txBytes = sse_decode_u_64(deserializer);
    var var_rxBytes = sse_decode_u_64(deserializer);
    var var_nPeersAttempted = sse_decode_u_32(deserializer);
    var var_nPeersAccepted = sse_decode_u_32(deserializer);
    var var_outcome = sse_decode_round_outcome(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    return RoundSummary(
      roundId: var_roundId,
      sessionId: var_sessionId,
      nRecords: var_nRecords,
      roundKind: var_roundKind,
      treeIdx: var_treeIdx,
      depth: var_depth,
      pollUs: var_pollUs,
      computeUs: var_computeUs,
      submitUs: var_submitUs,
      txBytes: var_txBytes,
      rxBytes: var_rxBytes,
      nPeersAttempted: var_nPeersAttempted,
      nPeersAccepted: var_nPeersAccepted,
      outcome: var_outcome,
      lastError: var_lastError,
    );
  }

  @protected
  SessionListResult sse_decode_session_list_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessions = sse_decode_list_session_summary(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    return SessionListResult(sessions: var_sessions, lastError: var_lastError);
  }

  @protected
  SessionPhase sse_decode_session_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SessionPhase.values[inner];
  }

  @protected
  SessionSummary sse_decode_session_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_phase = sse_decode_session_phase(deserializer);
    var var_nFeatures = sse_decode_u_32(deserializer);
    var var_datasetId = sse_decode_String(deserializer);
    return SessionSummary(
      sessionId: var_sessionId,
      phase: var_phase,
      nFeatures: var_nFeatures,
      datasetId: var_datasetId,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_round_summary_Sse(
    RustStreamSink<RoundSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_round_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_batch_participation_result(
    BatchParticipationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.records, serializer);
    sse_encode_u_32(self.completed, serializer);
    sse_encode_u_32(self.roundsTotal, serializer);
    sse_encode_opt_String(self.lastError, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_idle_poll(
    IdlePoll self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_idle_poll(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_round_summary(
    RoundSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_round_summary(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_client_platform(
    ClientPlatform self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_enroll_result(EnrollResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.lastError, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_idle_poll(IdlePoll self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_u_64(self.pollUs, serializer);
  }

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(
      self is Float64List ? self : Float64List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_list_prim_f_64_strict_f_64(
    List<(Float64List, double)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_list_prim_f_64_strict_f_64(item, serializer);
    }
  }

  @protected
  void sse_encode_list_session_summary(
    List<SessionSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_session_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_idle_poll(
    IdlePoll? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_idle_poll(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_round_summary(
    RoundSummary? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_round_summary(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_participation_result(
    ParticipationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.completed, serializer);
    sse_encode_u_32(self.roundsSubmitted, serializer);
    sse_encode_opt_String(self.lastError, serializer);
    sse_encode_u_64(self.computeUs, serializer);
    sse_encode_u_64(self.submitUs, serializer);
  }

  @protected
  void sse_encode_record_list_prim_f_64_strict_f_64(
    (Float64List, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_64_strict(self.$1, serializer);
    sse_encode_f_64(self.$2, serializer);
  }

  @protected
  void sse_encode_register_result(
    RegisterResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.lastError, serializer);
  }

  @protected
  void sse_encode_round_kind(RoundKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_round_outcome(RoundOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_round_step_outcome(
    RoundStepOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_round_step_result(
    RoundStepResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_round_step_outcome(self.outcome, serializer);
    sse_encode_u_64(self.roundId, serializer);
    sse_encode_opt_String(self.sessionId, serializer);
    sse_encode_u_64(self.lastSeenRoundId, serializer);
    sse_encode_opt_box_autoadd_round_summary(self.summary, serializer);
    sse_encode_opt_box_autoadd_idle_poll(self.idle, serializer);
    sse_encode_opt_String(self.lastError, serializer);
  }

  @protected
  void sse_encode_round_summary(RoundSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.roundId, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_u_32(self.nRecords, serializer);
    sse_encode_round_kind(self.roundKind, serializer);
    sse_encode_opt_box_autoadd_u_32(self.treeIdx, serializer);
    sse_encode_opt_box_autoadd_u_32(self.depth, serializer);
    sse_encode_u_64(self.pollUs, serializer);
    sse_encode_u_64(self.computeUs, serializer);
    sse_encode_u_64(self.submitUs, serializer);
    sse_encode_u_64(self.txBytes, serializer);
    sse_encode_u_64(self.rxBytes, serializer);
    sse_encode_u_32(self.nPeersAttempted, serializer);
    sse_encode_u_32(self.nPeersAccepted, serializer);
    sse_encode_round_outcome(self.outcome, serializer);
    sse_encode_opt_String(self.lastError, serializer);
  }

  @protected
  void sse_encode_session_list_result(
    SessionListResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_session_summary(self.sessions, serializer);
    sse_encode_opt_String(self.lastError, serializer);
  }

  @protected
  void sse_encode_session_phase(SessionPhase self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_session_summary(
    SessionSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_session_phase(self.phase, serializer);
    sse_encode_u_32(self.nFeatures, serializer);
    sse_encode_String(self.datasetId, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
