// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mobile.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<RoundSummary> dco_decode_StreamSink_round_summary_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BatchParticipationResult dco_decode_batch_participation_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  IdlePoll dco_decode_box_autoadd_idle_poll(dynamic raw);

  @protected
  RoundSummary dco_decode_box_autoadd_round_summary(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ClientPlatform dco_decode_client_platform(dynamic raw);

  @protected
  EnrollResult dco_decode_enroll_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IdlePoll dco_decode_idle_poll(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(Float64List, double)> dco_decode_list_record_list_prim_f_64_strict_f_64(
    dynamic raw,
  );

  @protected
  List<SessionSummary> dco_decode_list_session_summary(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  IdlePoll? dco_decode_opt_box_autoadd_idle_poll(dynamic raw);

  @protected
  RoundSummary? dco_decode_opt_box_autoadd_round_summary(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ParticipationResult dco_decode_participation_result(dynamic raw);

  @protected
  (Float64List, double) dco_decode_record_list_prim_f_64_strict_f_64(
    dynamic raw,
  );

  @protected
  RegisterResult dco_decode_register_result(dynamic raw);

  @protected
  RoundKind dco_decode_round_kind(dynamic raw);

  @protected
  RoundOutcome dco_decode_round_outcome(dynamic raw);

  @protected
  RoundStepOutcome dco_decode_round_step_outcome(dynamic raw);

  @protected
  RoundStepResult dco_decode_round_step_result(dynamic raw);

  @protected
  RoundSummary dco_decode_round_summary(dynamic raw);

  @protected
  SessionListResult dco_decode_session_list_result(dynamic raw);

  @protected
  SessionPhase dco_decode_session_phase(dynamic raw);

  @protected
  SessionSummary dco_decode_session_summary(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<RoundSummary> sse_decode_StreamSink_round_summary_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BatchParticipationResult sse_decode_batch_participation_result(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  IdlePoll sse_decode_box_autoadd_idle_poll(SseDeserializer deserializer);

  @protected
  RoundSummary sse_decode_box_autoadd_round_summary(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ClientPlatform sse_decode_client_platform(SseDeserializer deserializer);

  @protected
  EnrollResult sse_decode_enroll_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IdlePoll sse_decode_idle_poll(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(Float64List, double)> sse_decode_list_record_list_prim_f_64_strict_f_64(
    SseDeserializer deserializer,
  );

  @protected
  List<SessionSummary> sse_decode_list_session_summary(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  IdlePoll? sse_decode_opt_box_autoadd_idle_poll(SseDeserializer deserializer);

  @protected
  RoundSummary? sse_decode_opt_box_autoadd_round_summary(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ParticipationResult sse_decode_participation_result(
    SseDeserializer deserializer,
  );

  @protected
  (Float64List, double) sse_decode_record_list_prim_f_64_strict_f_64(
    SseDeserializer deserializer,
  );

  @protected
  RegisterResult sse_decode_register_result(SseDeserializer deserializer);

  @protected
  RoundKind sse_decode_round_kind(SseDeserializer deserializer);

  @protected
  RoundOutcome sse_decode_round_outcome(SseDeserializer deserializer);

  @protected
  RoundStepOutcome sse_decode_round_step_outcome(SseDeserializer deserializer);

  @protected
  RoundStepResult sse_decode_round_step_result(SseDeserializer deserializer);

  @protected
  RoundSummary sse_decode_round_summary(SseDeserializer deserializer);

  @protected
  SessionListResult sse_decode_session_list_result(
    SseDeserializer deserializer,
  );

  @protected
  SessionPhase sse_decode_session_phase(SseDeserializer deserializer);

  @protected
  SessionSummary sse_decode_session_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_round_summary_Sse(
    RustStreamSink<RoundSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_batch_participation_result(
    BatchParticipationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_idle_poll(
    IdlePoll self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_round_summary(
    RoundSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_client_platform(
    ClientPlatform self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_enroll_result(EnrollResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_idle_poll(IdlePoll self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_list_prim_f_64_strict_f_64(
    List<(Float64List, double)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_summary(
    List<SessionSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_idle_poll(
    IdlePoll? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_round_summary(
    RoundSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_participation_result(
    ParticipationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_list_prim_f_64_strict_f_64(
    (Float64List, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_register_result(
    RegisterResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_round_kind(RoundKind self, SseSerializer serializer);

  @protected
  void sse_encode_round_outcome(RoundOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_round_step_outcome(
    RoundStepOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_round_step_result(
    RoundStepResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_round_summary(RoundSummary self, SseSerializer serializer);

  @protected
  void sse_encode_session_list_result(
    SessionListResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_phase(SessionPhase self, SseSerializer serializer);

  @protected
  void sse_encode_session_summary(
    SessionSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
