// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_round_summary`, `idle_poll_from`, `round_summary_from`, `session_summary_from`, `watermark_to_report`

/// Subscribe before calling `participate`: each submitted round then arrives
/// as one [`RoundSummary`]. The sink auto-closes when Dart drops the stream.
Stream<RoundSummary> createRoundSummaryStream() =>
    RustLib.instance.api.crateApiMobileCreateRoundSummaryStream();

/// Drive this device through one full training session: enroll, then poll,
/// compute and submit until it completes. Shareholder endpoints and the Shamir
/// threshold are learned from the enroll response.
///
/// `session_id` picks the session, `None` the aggregator's only one. `ca_pem`
/// pins TLS for an `https://` endpoint; `None` connects in plaintext, the
/// loopback default. Dart chooses by scheme and supplies the bundled CA.
Future<ParticipationResult> participate({
  required String aggEndpoint,
  required String idToken,
  String? sessionId,
  required List<double> featureRow,
  required double label,
  required bool hidePath,
  Uint8List? caPem,
}) => RustLib.instance.api.crateApiMobileParticipate(
  aggEndpoint: aggEndpoint,
  idToken: idToken,
  sessionId: sessionId,
  featureRow: featureRow,
  label: label,
  hidePath: hidePath,
  caPem: caPem,
);

/// Drive this device's whole record slice through one session as one protocol
/// client: `records` is folded into a single commitment per round, shared once
/// rather than once per record, so per-round message size is independent of
/// batch size and only compute scales with it. Submitted rounds go to the same
/// summary stream `participate` feeds.
///
/// `session_id` and `ca_pem` behave as in [`participate`].
Future<BatchParticipationResult> participateBatch({
  required String aggEndpoint,
  required String idToken,
  String? sessionId,
  required List<(Float64List, double)> records,
  required bool hidePath,
  Uint8List? caPem,
}) => RustLib.instance.api.crateApiMobileParticipateBatch(
  aggEndpoint: aggEndpoint,
  idToken: idToken,
  sessionId: sessionId,
  records: records,
  hidePath: hidePath,
  caPem: caPem,
);

/// Register this device's FCM token, bound to the identity `id_token` proves.
/// Called on sign-in and on every token refresh. A device participating over
/// TLS must register over TLS, so Dart threads the same `ca_pem` through
/// both.
Future<RegisterResult> registerDevice({
  required String aggEndpoint,
  required String idToken,
  required String fcmToken,
  required ClientPlatform platform,
  Uint8List? caPem,
}) => RustLib.instance.api.crateApiMobileRegisterDevice(
  aggEndpoint: aggEndpoint,
  idToken: idToken,
  fcmToken: fcmToken,
  platform: platform,
  caPem: caPem,
);

/// Records this device's interest, since the notify tick only wakes enrolled
/// devices. Best-effort from the join action: the wake loop's own enroll
/// refreshes the same row, so a failure here delays only the first push.
Future<EnrollResult> enrollSession({
  required String aggEndpoint,
  required String idToken,
  required String sessionId,
  Uint8List? caPem,
}) => RustLib.instance.api.crateApiMobileEnrollSession(
  aggEndpoint: aggEndpoint,
  idToken: idToken,
  sessionId: sessionId,
  caPem: caPem,
);

/// Every session the aggregator is hosting, so the app can offer a choice
/// before joining one. `ca_pem` behaves as in [`participate`]; on failure the
/// session list comes back empty.
Future<SessionListResult> listSessions({
  required String aggEndpoint,
  required String idToken,
  Uint8List? caPem,
}) => RustLib.instance.api.crateApiMobileListSessions(
  aggEndpoint: aggEndpoint,
  idToken: idToken,
  caPem: caPem,
);

/// Advance a resumed session by exactly one round: enroll at
/// `last_seen_round_id`, take one step, and report what happened plus the
/// watermark to persist. The seam a background wake drives: one wake, one
/// step, no polling loop inside.
///
/// `session_id` and `ca_pem` behave as in [`participate`]; an enroll or step
/// failure arrives as `outcome: Error` with `last_error` set.
Future<RoundStepResult> stepSession({
  required String aggEndpoint,
  required String idToken,
  String? sessionId,
  required List<(Float64List, double)> records,
  required bool hidePath,
  Uint8List? caPem,
  required BigInt lastSeenRoundId,
}) => RustLib.instance.api.crateApiMobileStepSession(
  aggEndpoint: aggEndpoint,
  idToken: idToken,
  sessionId: sessionId,
  records: records,
  hidePath: hidePath,
  caPem: caPem,
  lastSeenRoundId: lastSeenRoundId,
);

/// One protocol client contributes the device's whole record slice under one
/// commitment per round. Per-round detail arrives on the summary stream.
class BatchParticipationResult {
  /// The batch size: how many records this device submitted.
  final int records;

  /// 1 if the client drove its session to `Completed`, else 0.
  final int completed;

  /// Rounds this client submitted.
  final int roundsTotal;

  /// The client's error, if it failed rather than completed.
  final String? lastError;

  const BatchParticipationResult({
    required this.records,
    required this.completed,
    required this.roundsTotal,
    this.lastError,
  });

  @override
  int get hashCode =>
      records.hashCode ^
      completed.hashCode ^
      roundsTotal.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchParticipationResult &&
          runtimeType == other.runtimeType &&
          records == other.records &&
          completed == other.completed &&
          roundsTotal == other.roundsTotal &&
          lastError == other.lastError;
}

/// Its own enum, so no pbr-client type crosses the bridge.
enum ClientPlatform { android, ios }

/// Plain data across the bridge.
class EnrollResult {
  final bool ok;
  final String? lastError;

  const EnrollResult({required this.ok, this.lastError});

  @override
  int get hashCode => ok.hashCode ^ lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnrollResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          lastError == other.lastError;
}

/// A `step_session` wake whose poll found no new context. Leaner than
/// [`RoundSummary`]: nothing was computed or submitted, so there is no round
/// id, no wire detail, and no timing beyond the poll.
class IdlePoll {
  /// Keys the check-in document on the same session as a submitted round.
  final String sessionId;

  /// Wall time spent waiting on the `PollSession` RPC, in microseconds.
  final BigInt pollUs;

  const IdlePoll({required this.sessionId, required this.pollUs});

  @override
  int get hashCode => sessionId.hashCode ^ pollUs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdlePoll &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          pollUs == other.pollUs;
}

/// Plain fields: no proto types cross the bridge.
class ParticipationResult {
  final bool completed;
  final int roundsSubmitted;
  final String? lastError;

  /// Microseconds of share computation, summed over every `Submitted` step.
  final BigInt computeUs;

  /// Microseconds of shareholder fan-out, summed the same way.
  final BigInt submitUs;

  const ParticipationResult({
    required this.completed,
    required this.roundsSubmitted,
    this.lastError,
    required this.computeUs,
    required this.submitUs,
  });

  @override
  int get hashCode =>
      completed.hashCode ^
      roundsSubmitted.hashCode ^
      lastError.hashCode ^
      computeUs.hashCode ^
      submitUs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParticipationResult &&
          runtimeType == other.runtimeType &&
          completed == other.completed &&
          roundsSubmitted == other.roundsSubmitted &&
          lastError == other.lastError &&
          computeUs == other.computeUs &&
          submitUs == other.submitUs;
}

/// Plain fields: no proto types cross the bridge.
class RegisterResult {
  final bool ok;
  final String? lastError;

  const RegisterResult({required this.ok, this.lastError});

  @override
  int get hashCode => ok.hashCode ^ lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegisterResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          lastError == other.lastError;
}

/// FRB generates a Dart enum whose `.name` yields `stats` or `gradient`, which
/// the analysis pipeline keys on.
enum RoundKind { stats, gradient }

/// How a round's submission landed; `.name` yields `submitted` or
/// `belowThreshold`. Reaching fewer than the Shamir threshold of shareholders
/// is recorded, not fatal.
enum RoundOutcome { submitted, belowThreshold }

/// What one `step_session` wake observed.
enum RoundStepOutcome {
  /// A round was polled, computed and submitted; `summary` has the detail.
  submitted,

  /// No new round was open yet; try again after the server's poll hint.
  nothingNew,

  /// The aggregator reports the session complete; no further steps.
  completed,

  /// The aggregator reports the session failed; no further steps.
  failed,

  /// The step could not be completed; see `last_error`.
  error,
}

/// Outcome of one `step_session` call: exactly one wake's worth of progress
/// on a resumable session, crossing the FRB bridge as plain fields.
class RoundStepResult {
  final RoundStepOutcome outcome;

  /// The round id this step observed; 0 for `NothingNew`, `Error`, or a
  /// `Completed`/`Failed` outcome with no new round context.
  final BigInt roundId;

  /// The session this wake enrolled under; `None` only if `enroll_at` itself
  /// failed. Persist it alongside `last_seen_round_id` and pass both back: a
  /// watermark means nothing outside its own session. Without the pair, a
  /// device resuming after an aggregator restart can find the new session's
  /// round id equal to its stale watermark and park on `NothingNew`
  /// forever.
  final String? sessionId;

  /// The watermark to persist for the next wake. It advances only on
  /// `Submitted`; every other outcome, `Error` included, returns the input
  /// unchanged. `ClientSession` advances its own watermark as soon as it
  /// polls a context, before compute and submit, so a step can still fail
  /// after that point: reporting the advanced value would let a caller
  /// persist a round this device never finished, and skip it next wake.
  final BigInt lastSeenRoundId;
  final RoundSummary? summary;

  /// Only for `NothingNew`: the idle poll's session id and wall time, for a
  /// check-in document. `summary` is its `Submitted` counterpart.
  final IdlePoll? idle;
  final String? lastError;

  const RoundStepResult({
    required this.outcome,
    required this.roundId,
    this.sessionId,
    required this.lastSeenRoundId,
    this.summary,
    this.idle,
    this.lastError,
  });

  @override
  int get hashCode =>
      outcome.hashCode ^
      roundId.hashCode ^
      sessionId.hashCode ^
      lastSeenRoundId.hashCode ^
      summary.hashCode ^
      idle.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoundStepResult &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          roundId == other.roundId &&
          sessionId == other.sessionId &&
          lastSeenRoundId == other.lastSeenRoundId &&
          summary == other.summary &&
          idle == other.idle &&
          lastError == other.lastError;
}

/// One submitted round's mobile-side measurements, one per round, each
/// becoming a `paperSimRoundMetrics` document. `tree_idx` and `depth` are
/// decoded from `round_id` in Rust; `last_error` is a per-round note.
class RoundSummary {
  final BigInt roundId;

  /// Keys these metrics on the same session as the aggregator's per-tree
  /// quality metrics.
  final String sessionId;

  /// How many records the one client folded into its commitment.
  final int nRecords;
  final RoundKind roundKind;
  final int? treeIdx;
  final int? depth;
  final BigInt pollUs;
  final BigInt computeUs;
  final BigInt submitUs;
  final BigInt txBytes;
  final BigInt rxBytes;
  final int nPeersAttempted;
  final int nPeersAccepted;
  final RoundOutcome outcome;
  final String? lastError;

  const RoundSummary({
    required this.roundId,
    required this.sessionId,
    required this.nRecords,
    required this.roundKind,
    this.treeIdx,
    this.depth,
    required this.pollUs,
    required this.computeUs,
    required this.submitUs,
    required this.txBytes,
    required this.rxBytes,
    required this.nPeersAttempted,
    required this.nPeersAccepted,
    required this.outcome,
    this.lastError,
  });

  @override
  int get hashCode =>
      roundId.hashCode ^
      sessionId.hashCode ^
      nRecords.hashCode ^
      roundKind.hashCode ^
      treeIdx.hashCode ^
      depth.hashCode ^
      pollUs.hashCode ^
      computeUs.hashCode ^
      submitUs.hashCode ^
      txBytes.hashCode ^
      rxBytes.hashCode ^
      nPeersAttempted.hashCode ^
      nPeersAccepted.hashCode ^
      outcome.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoundSummary &&
          runtimeType == other.runtimeType &&
          roundId == other.roundId &&
          sessionId == other.sessionId &&
          nRecords == other.nRecords &&
          roundKind == other.roundKind &&
          treeIdx == other.treeIdx &&
          depth == other.depth &&
          pollUs == other.pollUs &&
          computeUs == other.computeUs &&
          submitUs == other.submitUs &&
          txBytes == other.txBytes &&
          rxBytes == other.rxBytes &&
          nPeersAttempted == other.nPeersAttempted &&
          nPeersAccepted == other.nPeersAccepted &&
          outcome == other.outcome &&
          lastError == other.lastError;
}

/// Plain fields: no proto types cross the bridge.
class SessionListResult {
  final List<SessionSummary> sessions;
  final String? lastError;

  const SessionListResult({required this.sessions, this.lastError});

  @override
  int get hashCode => sessions.hashCode ^ lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionListResult &&
          runtimeType == other.runtimeType &&
          sessions == other.sessions &&
          lastError == other.lastError;
}

/// Which phase a hosted session is in, as reported by `list_sessions`.
enum SessionPhase { statsPending, training, completed, failed }

/// One session the app can choose to join, as reported by `list_sessions`.
class SessionSummary {
  final String sessionId;
  final SessionPhase phase;
  final int nFeatures;

  /// Which dataset a device selects its records by; empty for a
  /// dataset-less session. `n_features` cross-checks this id's expected
  /// width and is never a substitute selector.
  final String datasetId;

  const SessionSummary({
    required this.sessionId,
    required this.phase,
    required this.nFeatures,
    required this.datasetId,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      phase.hashCode ^
      nFeatures.hashCode ^
      datasetId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSummary &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          phase == other.phase &&
          nFeatures == other.nFeatures &&
          datasetId == other.datasetId;
}
