# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import privateboost_pb2 as privateboost__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in privateboost_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShareholderServiceStub(object):
    """-- ShareholderService --

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitStats = channel.unary_unary(
                '/privateboost.ShareholderService/SubmitStats',
                request_serializer=privateboost__pb2.SubmitStatsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.SubmitStatsResponse.FromString,
                _registered_method=True)
        self.SubmitGradients = channel.unary_unary(
                '/privateboost.ShareholderService/SubmitGradients',
                request_serializer=privateboost__pb2.SubmitGradientsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.SubmitGradientsResponse.FromString,
                _registered_method=True)
        self.GetStatsCommitments = channel.unary_unary(
                '/privateboost.ShareholderService/GetStatsCommitments',
                request_serializer=privateboost__pb2.GetStatsCommitmentsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetStatsCommitmentsResponse.FromString,
                _registered_method=True)
        self.GetGradientCommitments = channel.unary_unary(
                '/privateboost.ShareholderService/GetGradientCommitments',
                request_serializer=privateboost__pb2.GetGradientCommitmentsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetGradientCommitmentsResponse.FromString,
                _registered_method=True)
        self.GetGradientNodeIds = channel.unary_unary(
                '/privateboost.ShareholderService/GetGradientNodeIds',
                request_serializer=privateboost__pb2.GetGradientNodeIdsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetGradientNodeIdsResponse.FromString,
                _registered_method=True)
        self.GetStatsSum = channel.unary_unary(
                '/privateboost.ShareholderService/GetStatsSum',
                request_serializer=privateboost__pb2.GetStatsSumRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetStatsSumResponse.FromString,
                _registered_method=True)
        self.GetGradientsSum = channel.unary_unary(
                '/privateboost.ShareholderService/GetGradientsSum',
                request_serializer=privateboost__pb2.GetGradientsSumRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetGradientsSumResponse.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/privateboost.ShareholderService/SubmitResult',
                request_serializer=privateboost__pb2.SubmitResultRequest.SerializeToString,
                response_deserializer=privateboost__pb2.SubmitResultResponse.FromString,
                _registered_method=True)
        self.GetConsensusBins = channel.unary_unary(
                '/privateboost.ShareholderService/GetConsensusBins',
                request_serializer=privateboost__pb2.GetConsensusBinsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetConsensusBinsResponse.FromString,
                _registered_method=True)
        self.GetConsensusSplits = channel.unary_unary(
                '/privateboost.ShareholderService/GetConsensusSplits',
                request_serializer=privateboost__pb2.GetConsensusSplitsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetConsensusSplitsResponse.FromString,
                _registered_method=True)
        self.GetConsensusModel = channel.unary_unary(
                '/privateboost.ShareholderService/GetConsensusModel',
                request_serializer=privateboost__pb2.GetConsensusModelRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetConsensusModelResponse.FromString,
                _registered_method=True)
        self.GetRunState = channel.unary_unary(
                '/privateboost.ShareholderService/GetRunState',
                request_serializer=privateboost__pb2.GetRunStateRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetRunStateResponse.FromString,
                _registered_method=True)


class ShareholderServiceServicer(object):
    """-- ShareholderService --

    """

    def SubmitStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitGradients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatsCommitments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGradientCommitments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGradientNodeIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatsSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGradientsSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsensusBins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsensusSplits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsensusModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShareholderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitStats': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitStats,
                    request_deserializer=privateboost__pb2.SubmitStatsRequest.FromString,
                    response_serializer=privateboost__pb2.SubmitStatsResponse.SerializeToString,
            ),
            'SubmitGradients': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGradients,
                    request_deserializer=privateboost__pb2.SubmitGradientsRequest.FromString,
                    response_serializer=privateboost__pb2.SubmitGradientsResponse.SerializeToString,
            ),
            'GetStatsCommitments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatsCommitments,
                    request_deserializer=privateboost__pb2.GetStatsCommitmentsRequest.FromString,
                    response_serializer=privateboost__pb2.GetStatsCommitmentsResponse.SerializeToString,
            ),
            'GetGradientCommitments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGradientCommitments,
                    request_deserializer=privateboost__pb2.GetGradientCommitmentsRequest.FromString,
                    response_serializer=privateboost__pb2.GetGradientCommitmentsResponse.SerializeToString,
            ),
            'GetGradientNodeIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGradientNodeIds,
                    request_deserializer=privateboost__pb2.GetGradientNodeIdsRequest.FromString,
                    response_serializer=privateboost__pb2.GetGradientNodeIdsResponse.SerializeToString,
            ),
            'GetStatsSum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatsSum,
                    request_deserializer=privateboost__pb2.GetStatsSumRequest.FromString,
                    response_serializer=privateboost__pb2.GetStatsSumResponse.SerializeToString,
            ),
            'GetGradientsSum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGradientsSum,
                    request_deserializer=privateboost__pb2.GetGradientsSumRequest.FromString,
                    response_serializer=privateboost__pb2.GetGradientsSumResponse.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=privateboost__pb2.SubmitResultRequest.FromString,
                    response_serializer=privateboost__pb2.SubmitResultResponse.SerializeToString,
            ),
            'GetConsensusBins': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsensusBins,
                    request_deserializer=privateboost__pb2.GetConsensusBinsRequest.FromString,
                    response_serializer=privateboost__pb2.GetConsensusBinsResponse.SerializeToString,
            ),
            'GetConsensusSplits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsensusSplits,
                    request_deserializer=privateboost__pb2.GetConsensusSplitsRequest.FromString,
                    response_serializer=privateboost__pb2.GetConsensusSplitsResponse.SerializeToString,
            ),
            'GetConsensusModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsensusModel,
                    request_deserializer=privateboost__pb2.GetConsensusModelRequest.FromString,
                    response_serializer=privateboost__pb2.GetConsensusModelResponse.SerializeToString,
            ),
            'GetRunState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunState,
                    request_deserializer=privateboost__pb2.GetRunStateRequest.FromString,
                    response_serializer=privateboost__pb2.GetRunStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'privateboost.ShareholderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('privateboost.ShareholderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShareholderService(object):
    """-- ShareholderService --

    """

    @staticmethod
    def SubmitStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/SubmitStats',
            privateboost__pb2.SubmitStatsRequest.SerializeToString,
            privateboost__pb2.SubmitStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitGradients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/SubmitGradients',
            privateboost__pb2.SubmitGradientsRequest.SerializeToString,
            privateboost__pb2.SubmitGradientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatsCommitments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetStatsCommitments',
            privateboost__pb2.GetStatsCommitmentsRequest.SerializeToString,
            privateboost__pb2.GetStatsCommitmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGradientCommitments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetGradientCommitments',
            privateboost__pb2.GetGradientCommitmentsRequest.SerializeToString,
            privateboost__pb2.GetGradientCommitmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGradientNodeIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetGradientNodeIds',
            privateboost__pb2.GetGradientNodeIdsRequest.SerializeToString,
            privateboost__pb2.GetGradientNodeIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatsSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetStatsSum',
            privateboost__pb2.GetStatsSumRequest.SerializeToString,
            privateboost__pb2.GetStatsSumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGradientsSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetGradientsSum',
            privateboost__pb2.GetGradientsSumRequest.SerializeToString,
            privateboost__pb2.GetGradientsSumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/SubmitResult',
            privateboost__pb2.SubmitResultRequest.SerializeToString,
            privateboost__pb2.SubmitResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsensusBins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetConsensusBins',
            privateboost__pb2.GetConsensusBinsRequest.SerializeToString,
            privateboost__pb2.GetConsensusBinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsensusSplits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetConsensusSplits',
            privateboost__pb2.GetConsensusSplitsRequest.SerializeToString,
            privateboost__pb2.GetConsensusSplitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsensusModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetConsensusModel',
            privateboost__pb2.GetConsensusModelRequest.SerializeToString,
            privateboost__pb2.GetConsensusModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetRunState',
            privateboost__pb2.GetRunStateRequest.SerializeToString,
            privateboost__pb2.GetRunStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorServiceStub(object):
    """-- CoordinatorService --

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRun = channel.unary_unary(
                '/privateboost.CoordinatorService/CreateRun',
                request_serializer=privateboost__pb2.CreateRunRequest.SerializeToString,
                response_deserializer=privateboost__pb2.CreateRunResponse.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/privateboost.CoordinatorService/CancelRun',
                request_serializer=privateboost__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=privateboost__pb2.CancelRunResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/privateboost.CoordinatorService/ListRuns',
                request_serializer=privateboost__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.GetRunConfig = channel.unary_unary(
                '/privateboost.CoordinatorService/GetRunConfig',
                request_serializer=privateboost__pb2.GetRunConfigRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetRunConfigResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """-- CoordinatorService --

    """

    def CreateRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRun,
                    request_deserializer=privateboost__pb2.CreateRunRequest.FromString,
                    response_serializer=privateboost__pb2.CreateRunResponse.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=privateboost__pb2.CancelRunRequest.FromString,
                    response_serializer=privateboost__pb2.CancelRunResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=privateboost__pb2.ListRunsRequest.FromString,
                    response_serializer=privateboost__pb2.ListRunsResponse.SerializeToString,
            ),
            'GetRunConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunConfig,
                    request_deserializer=privateboost__pb2.GetRunConfigRequest.FromString,
                    response_serializer=privateboost__pb2.GetRunConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'privateboost.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('privateboost.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """-- CoordinatorService --

    """

    @staticmethod
    def CreateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.CoordinatorService/CreateRun',
            privateboost__pb2.CreateRunRequest.SerializeToString,
            privateboost__pb2.CreateRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.CoordinatorService/CancelRun',
            privateboost__pb2.CancelRunRequest.SerializeToString,
            privateboost__pb2.CancelRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.CoordinatorService/ListRuns',
            privateboost__pb2.ListRunsRequest.SerializeToString,
            privateboost__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.CoordinatorService/GetRunConfig',
            privateboost__pb2.GetRunConfigRequest.SerializeToString,
            privateboost__pb2.GetRunConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
