# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from privateboost.grpc import privateboost_pb2 as privateboost__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in privateboost_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShareholderServiceStub(object):
    """-- ShareholderService --

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitStats = channel.unary_unary(
                '/privateboost.ShareholderService/SubmitStats',
                request_serializer=privateboost__pb2.SubmitStatsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.SubmitStatsResponse.FromString,
                _registered_method=True)
        self.SubmitGradients = channel.unary_unary(
                '/privateboost.ShareholderService/SubmitGradients',
                request_serializer=privateboost__pb2.SubmitGradientsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.SubmitGradientsResponse.FromString,
                _registered_method=True)
        self.GetStatsCommitments = channel.unary_unary(
                '/privateboost.ShareholderService/GetStatsCommitments',
                request_serializer=privateboost__pb2.GetStatsCommitmentsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetStatsCommitmentsResponse.FromString,
                _registered_method=True)
        self.GetGradientCommitments = channel.unary_unary(
                '/privateboost.ShareholderService/GetGradientCommitments',
                request_serializer=privateboost__pb2.GetGradientCommitmentsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetGradientCommitmentsResponse.FromString,
                _registered_method=True)
        self.GetGradientNodeIds = channel.unary_unary(
                '/privateboost.ShareholderService/GetGradientNodeIds',
                request_serializer=privateboost__pb2.GetGradientNodeIdsRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetGradientNodeIdsResponse.FromString,
                _registered_method=True)
        self.GetStatsSum = channel.unary_unary(
                '/privateboost.ShareholderService/GetStatsSum',
                request_serializer=privateboost__pb2.GetStatsSumRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetStatsSumResponse.FromString,
                _registered_method=True)
        self.GetGradientsSum = channel.unary_unary(
                '/privateboost.ShareholderService/GetGradientsSum',
                request_serializer=privateboost__pb2.GetGradientsSumRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetGradientsSumResponse.FromString,
                _registered_method=True)
        self.CancelSession = channel.unary_unary(
                '/privateboost.ShareholderService/CancelSession',
                request_serializer=privateboost__pb2.CancelSessionRequest.SerializeToString,
                response_deserializer=privateboost__pb2.CancelSessionResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/privateboost.ShareholderService/Reset',
                request_serializer=privateboost__pb2.ResetRequest.SerializeToString,
                response_deserializer=privateboost__pb2.ResetResponse.FromString,
                _registered_method=True)


class ShareholderServiceServicer(object):
    """-- ShareholderService --

    """

    def SubmitStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitGradients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatsCommitments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGradientCommitments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGradientNodeIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatsSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGradientsSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShareholderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitStats': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitStats,
                    request_deserializer=privateboost__pb2.SubmitStatsRequest.FromString,
                    response_serializer=privateboost__pb2.SubmitStatsResponse.SerializeToString,
            ),
            'SubmitGradients': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGradients,
                    request_deserializer=privateboost__pb2.SubmitGradientsRequest.FromString,
                    response_serializer=privateboost__pb2.SubmitGradientsResponse.SerializeToString,
            ),
            'GetStatsCommitments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatsCommitments,
                    request_deserializer=privateboost__pb2.GetStatsCommitmentsRequest.FromString,
                    response_serializer=privateboost__pb2.GetStatsCommitmentsResponse.SerializeToString,
            ),
            'GetGradientCommitments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGradientCommitments,
                    request_deserializer=privateboost__pb2.GetGradientCommitmentsRequest.FromString,
                    response_serializer=privateboost__pb2.GetGradientCommitmentsResponse.SerializeToString,
            ),
            'GetGradientNodeIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGradientNodeIds,
                    request_deserializer=privateboost__pb2.GetGradientNodeIdsRequest.FromString,
                    response_serializer=privateboost__pb2.GetGradientNodeIdsResponse.SerializeToString,
            ),
            'GetStatsSum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatsSum,
                    request_deserializer=privateboost__pb2.GetStatsSumRequest.FromString,
                    response_serializer=privateboost__pb2.GetStatsSumResponse.SerializeToString,
            ),
            'GetGradientsSum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGradientsSum,
                    request_deserializer=privateboost__pb2.GetGradientsSumRequest.FromString,
                    response_serializer=privateboost__pb2.GetGradientsSumResponse.SerializeToString,
            ),
            'CancelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSession,
                    request_deserializer=privateboost__pb2.CancelSessionRequest.FromString,
                    response_serializer=privateboost__pb2.CancelSessionResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=privateboost__pb2.ResetRequest.FromString,
                    response_serializer=privateboost__pb2.ResetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'privateboost.ShareholderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('privateboost.ShareholderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShareholderService(object):
    """-- ShareholderService --

    """

    @staticmethod
    def SubmitStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/SubmitStats',
            privateboost__pb2.SubmitStatsRequest.SerializeToString,
            privateboost__pb2.SubmitStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitGradients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/SubmitGradients',
            privateboost__pb2.SubmitGradientsRequest.SerializeToString,
            privateboost__pb2.SubmitGradientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatsCommitments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetStatsCommitments',
            privateboost__pb2.GetStatsCommitmentsRequest.SerializeToString,
            privateboost__pb2.GetStatsCommitmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGradientCommitments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetGradientCommitments',
            privateboost__pb2.GetGradientCommitmentsRequest.SerializeToString,
            privateboost__pb2.GetGradientCommitmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGradientNodeIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetGradientNodeIds',
            privateboost__pb2.GetGradientNodeIdsRequest.SerializeToString,
            privateboost__pb2.GetGradientNodeIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatsSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetStatsSum',
            privateboost__pb2.GetStatsSumRequest.SerializeToString,
            privateboost__pb2.GetStatsSumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGradientsSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/GetGradientsSum',
            privateboost__pb2.GetGradientsSumRequest.SerializeToString,
            privateboost__pb2.GetGradientsSumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/CancelSession',
            privateboost__pb2.CancelSessionRequest.SerializeToString,
            privateboost__pb2.CancelSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.ShareholderService/Reset',
            privateboost__pb2.ResetRequest.SerializeToString,
            privateboost__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AggregatorServiceStub(object):
    """-- AggregatorService --

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinSession = channel.unary_unary(
                '/privateboost.AggregatorService/JoinSession',
                request_serializer=privateboost__pb2.JoinSessionRequest.SerializeToString,
                response_deserializer=privateboost__pb2.JoinSessionResponse.FromString,
                _registered_method=True)
        self.CancelSession = channel.unary_unary(
                '/privateboost.AggregatorService/CancelSession',
                request_serializer=privateboost__pb2.CancelSessionRequest.SerializeToString,
                response_deserializer=privateboost__pb2.CancelSessionResponse.FromString,
                _registered_method=True)
        self.GetRoundState = channel.unary_unary(
                '/privateboost.AggregatorService/GetRoundState',
                request_serializer=privateboost__pb2.GetRoundStateRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetRoundStateResponse.FromString,
                _registered_method=True)
        self.GetTrainingState = channel.unary_unary(
                '/privateboost.AggregatorService/GetTrainingState',
                request_serializer=privateboost__pb2.GetTrainingStateRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetTrainingStateResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/privateboost.AggregatorService/GetModel',
                request_serializer=privateboost__pb2.GetModelRequest.SerializeToString,
                response_deserializer=privateboost__pb2.GetModelResponse.FromString,
                _registered_method=True)


class AggregatorServiceServicer(object):
    """-- AggregatorService --

    """

    def JoinSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoundState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinSession': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinSession,
                    request_deserializer=privateboost__pb2.JoinSessionRequest.FromString,
                    response_serializer=privateboost__pb2.JoinSessionResponse.SerializeToString,
            ),
            'CancelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSession,
                    request_deserializer=privateboost__pb2.CancelSessionRequest.FromString,
                    response_serializer=privateboost__pb2.CancelSessionResponse.SerializeToString,
            ),
            'GetRoundState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoundState,
                    request_deserializer=privateboost__pb2.GetRoundStateRequest.FromString,
                    response_serializer=privateboost__pb2.GetRoundStateResponse.SerializeToString,
            ),
            'GetTrainingState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingState,
                    request_deserializer=privateboost__pb2.GetTrainingStateRequest.FromString,
                    response_serializer=privateboost__pb2.GetTrainingStateResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=privateboost__pb2.GetModelRequest.FromString,
                    response_serializer=privateboost__pb2.GetModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'privateboost.AggregatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('privateboost.AggregatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AggregatorService(object):
    """-- AggregatorService --

    """

    @staticmethod
    def JoinSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.AggregatorService/JoinSession',
            privateboost__pb2.JoinSessionRequest.SerializeToString,
            privateboost__pb2.JoinSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.AggregatorService/CancelSession',
            privateboost__pb2.CancelSessionRequest.SerializeToString,
            privateboost__pb2.CancelSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoundState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.AggregatorService/GetRoundState',
            privateboost__pb2.GetRoundStateRequest.SerializeToString,
            privateboost__pb2.GetRoundStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.AggregatorService/GetTrainingState',
            privateboost__pb2.GetTrainingStateRequest.SerializeToString,
            privateboost__pb2.GetTrainingStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privateboost.AggregatorService/GetModel',
            privateboost__pb2.GetModelRequest.SerializeToString,
            privateboost__pb2.GetModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
