"""Print the manuscript's fleet device table: per-device medians of the
four-device capture (results/fleet_round_metrics.csv). Print-and-paste,
matching binning_tables.py's role for the binning tables."""
import os

import pandas as pd

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")

# deviceModel (as reported by the platform) -> (display name, OS).
# Verify the keys against the CSV's uniques before trusting the output:
# the script fails loudly on an unmapped model rather than mislabeling it.
DEVICES = {
    "Google Pixel 9 Pro": ("Google Pixel 9 Pro", "Android"),
    "samsung SM-X200": ("Samsung Galaxy Tab A8", "Android"),
    "Lenovo TB328FU": ("Lenovo Tab M8", "Android"),
    "iPhone iPhone": ("Apple iPhone 13 Pro", "iOS"),
}


def main():
    df = pd.read_csv(os.path.join(RESULTS_DIR, "fleet_round_metrics.csv"))
    rounds = df[df["roundId"].notna()]
    unmapped = set(rounds["deviceModel"].unique()) - set(DEVICES)
    if unmapped:
        raise SystemExit(f"unmapped device models: {sorted(unmapped)}")

    print(r"% generated by analysis/fleet_table.py")
    for model, (name, os_name) in DEVICES.items():
        group = rounds[rounds["deviceModel"] == model]
        compute_ms = group["computeUs"].median() / 1000.0
        submit_ms = group["submitUs"].median() / 1000.0
        rss_mb = group["rssBytes"].median() / 1e6
        print(
            f"  {name} & {os_name} & {compute_ms:.1f} & {submit_ms:.0f} & {rss_mb:.0f} \\\\"
        )


if __name__ == "__main__":
    main()
